// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzsOFbWBMt707-4Cwg5R7gfaRRL74tplc',
    appId: '1:217276167017:web:0cf76b21d776c3997743f8',
    messagingSenderId: '217276167017',
    projectId: 'fcmnotify-804d1',
    authDomain: 'fcmnotify-804d1.firebaseapp.com',
    storageBucket: 'fcmnotify-804d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFWNjcxLZQ0Ydkq7iXVbbc_yvpich7jFg',
    appId: '1:217276167017:android:fceca6e62d8b19bf7743f8',
    messagingSenderId: '217276167017',
    projectId: 'fcmnotify-804d1',
    storageBucket: 'fcmnotify-804d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl8tcmC3m9Sya6ajO1DZVX4PlVhfu-dn4',
    appId: '1:217276167017:ios:bc86b2381428c7657743f8',
    messagingSenderId: '217276167017',
    projectId: 'fcmnotify-804d1',
    storageBucket: 'fcmnotify-804d1.appspot.com',
    iosBundleId: 'com.example.fcmtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl8tcmC3m9Sya6ajO1DZVX4PlVhfu-dn4',
    appId: '1:217276167017:ios:bc86b2381428c7657743f8',
    messagingSenderId: '217276167017',
    projectId: 'fcmnotify-804d1',
    storageBucket: 'fcmnotify-804d1.appspot.com',
    iosBundleId: 'com.example.fcmtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzsOFbWBMt707-4Cwg5R7gfaRRL74tplc',
    appId: '1:217276167017:web:e9fb2ee043b589a67743f8',
    messagingSenderId: '217276167017',
    projectId: 'fcmnotify-804d1',
    authDomain: 'fcmnotify-804d1.firebaseapp.com',
    storageBucket: 'fcmnotify-804d1.appspot.com',
  );

}